# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edf211ad5a0063b61806fac36c6198627b849532a599e40208d545a43d67a7993257f34849903b711f85081a647ea16b41cd47ba666f52731299e21658b20927

test:
  secret_key_base: 6bf1b7d8d303dc019779018ec3192516e7f971a39822714adf9ae480b784be9c616eb0888e63b84d5f22b42cc54cd1a3f28a319f3ff4029e683f16efb39a9630

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
